const mongoose = require('mongoose');
const crypto = require('crypto');

const orderSchema = new mongoose.Schema({
  orderNumber: {
    type: String,
    unique: true,
    required: false // Will be generated by pre-save middleware
  },
  trackingCode: {
    type: String,
    unique: true,
    required: false, // Will be generated by pre-save middleware
    uppercase: true
  },
  // Customer information - either logged in user or guest
  customer: {
    // For logged-in customers
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Customer',
      required: false
    },
    // For guest customers (required if userId is not provided)
    name: {
      type: String,
      required: function() {
        return !this.customer?.userId;
      },
      trim: true
    },
    email: {
      type: String,
      required: function() {
        return !this.customer?.userId;
      },
      lowercase: true,
      trim: true,
      match: [/^\S+@\S+\.\S+$/, 'Please provide a valid email']
    },
    phone: {
      type: String,
      required: function() {
        return !this.customer?.userId;
      },
      trim: true
    },
    // Address for delivery (can be different from customer's saved addresses)
    address: {
      street: String,
      city: String,
      state: String,
      zipCode: String,
      country: { type: String, default: 'USA' }
    },
    // Flag to indicate if this is a guest order
    isGuest: {
      type: Boolean,
      default: function() {
        return !this.customer?.userId;
      }
    }
  },
  items: [{
    productId: {
      type: String,
      required: true
    },
    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product'
    },
    name: {
      type: String,
      required: true
    },
    price: {
      type: Number,
      required: true,
      min: 0
    },
    quantity: {
      type: Number,
      required: true,
      min: 1
    },
    image: String,
    subtotal: Number
  }],
  totals: {
    subtotal: {
      type: Number,
      required: true,
      min: 0
    },
    tax: {
      type: Number,
      default: 0,
      min: 0
    },
    delivery: {
      type: Number,
      default: 0,
      min: 0
    },
    discount: {
      type: Number,
      default: 0,
      min: 0
    },
    total: {
      type: Number,
      required: true,
      min: 0
    }
  },
  delivery: {
    type: {
      type: String,
      enum: ['pickup', 'delivery'],
      required: true
    },
    scheduledFor: {
      type: Date,
      required: true
    },
    address: {
      street: String,
      city: String,
      state: String,
      zipCode: String
    },
    instructions: String,
    status: {
      type: String,
      enum: ['pending', 'preparing', 'ready', 'out_for_delivery', 'delivered'],
      default: 'pending'
    }
  },
  payment: {
    method: {
      type: String,
      enum: ['card', 'cash', 'paypal', 'stripe'],
      default: 'cash'
    },
    status: {
      type: String,
      enum: ['pending', 'paid', 'failed', 'refunded'],
      default: 'pending'
    },
    transactionId: String,
    stripeSessionId: String,
    stripePaymentIntentId: String,
    paidAt: Date,
    amount: Number,
    currency: {
      type: String,
      default: 'usd'
    }
  },
  status: {
    type: String,
    enum: ['pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled'],
    default: 'pending'
  },
  notes: String,
  specialInstructions: String
}, {
  timestamps: true
});

// Generate unique tracking code
function generateTrackingCode() {
  const prefix = 'AZ';
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = crypto.randomBytes(3).toString('hex').toUpperCase();
  return `${prefix}${timestamp}${random}`;
}

// Generate order number, tracking code, and calculate totals before saving
orderSchema.pre('save', async function() {
  console.log('🔧 Order pre-save middleware running...');
  
  try {
    // Generate order number if not exists
    if (!this.orderNumber) {
      console.log('🔧 Generating order number...');
      let orderNumber;
      let isUnique = false;
      
      // Ensure order number is unique
      while (!isUnique) {
        const date = new Date();
        const dateStr = date.getFullYear().toString().slice(-2) + 
                       (date.getMonth() + 1).toString().padStart(2, '0') + 
                       date.getDate().toString().padStart(2, '0');
        const randomNum = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
        orderNumber = `AZ${dateStr}${randomNum}`;
        
        const existingOrder = await this.constructor.findOne({ orderNumber });
        if (!existingOrder) {
          isUnique = true;
        }
      }
      
      this.orderNumber = orderNumber;
      console.log('🔧 Generated order number:', orderNumber);
    }
    
    // Generate tracking code if not exists
    if (!this.trackingCode) {
      console.log('🔧 Generating tracking code...');
      let trackingCode;
      let isUnique = false;
      
      // Ensure tracking code is unique
      while (!isUnique) {
        trackingCode = generateTrackingCode();
        const existingOrder = await this.constructor.findOne({ trackingCode });
        if (!existingOrder) {
          isUnique = true;
        }
      }
      
      this.trackingCode = trackingCode;
      console.log('🔧 Generated tracking code:', trackingCode);
    }
    
    // Calculate totals if not already set
    if (!this.totals || !this.totals.total) {
      console.log('🔧 Calculating totals...');
      
      // Initialize totals if not exists
      if (!this.totals) {
        this.totals = {};
      }
      
      // Calculate subtotal
      this.totals.subtotal = this.items.reduce((sum, item) => {
        item.subtotal = item.price * item.quantity;
        return sum + item.subtotal;
      }, 0);
      
      // Calculate tax (8.5%)
      this.totals.tax = Math.round(this.totals.subtotal * 0.085 * 100) / 100;
      
      // Calculate delivery fee
      if (this.delivery.type === 'delivery') {
        this.totals.delivery = this.totals.subtotal >= 50 ? 0 : 5.99;
      } else {
        this.totals.delivery = 0;
      }
      
      // Initialize discount if not exists
      if (!this.totals.discount) {
        this.totals.discount = 0;
      }
      
      // Calculate total
      this.totals.total = this.totals.subtotal + this.totals.tax + this.totals.delivery - this.totals.discount;
      this.totals.total = Math.round(this.totals.total * 100) / 100;
      
      console.log('🔧 Calculated totals:', this.totals);
    }
    
    console.log('🔧 Order pre-save middleware completed successfully');
  } catch (error) {
    console.error('🔧 Error in order pre-save middleware:', error);
    throw error;
  }
});



// Index for faster queries
orderSchema.index({ 'customer.email': 1 });
orderSchema.index({ status: 1, createdAt: -1 });
orderSchema.index({ 'delivery.scheduledFor': 1 });
orderSchema.index({ trackingCode: 1 }); // Index for tracking queries

module.exports = mongoose.model('Order', orderSchema);